export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
export const GET_CURRENCY = "GET_CURRENCY";

export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_GET_NUMBER = "CART_GET_NUMBER";

export const INCREASE_ITEM_QTY = "INCREASE_ITEM_QTY";

;